/*

REDUX TOOLE KIT -> RTK -> WHAT IS RTK DO -> GLOBAL STATE MANAGEMENT SYSTEM

    DATA  - STORE
    LOGIC - SLICE
    UI    - SELECTOR,DISPATCH

MVC FOLDER STRUCTURE
    M - MODEL -> NOW WHAT IS MODEL? -> DATA
    V - VIEW  -> NOW WHAT IS VIEW?  -> UI,SCREENS,COMPONENTS
    C - CONTROLLER -> NOW WHAT IS CONTROLLER -> LOGIC

STEP OF RTK ->
        STEP 1 CREATE REACT PROJECT. 
        STEP 2 CREATE FOLDER STRUCTURE BASE ON MVC.
        STEP 3 CREATE SLICE AND FIRST INSTALL THIS DEPENDENCIES -> NPM INSTALL @REDUXJS/TOOLKIT REACT-REDUX
        STEP 4 CREATE STORE 
        STEP 5 


WORK TO COMPLETE 
TWITTER
SIGNIN(AUTHENTICATE)/SIGNUP(NO DUPLICATE USER)
HOME -> ADD TWEET -> TWEET + USER NAME + TIME 
COMPLETE TWITTER APPLICATION WITH SAME TWITTER UI
DEADLINE -> FRIDAY 
*/
